apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job-parallel
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job