apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      name: ssd-monitor
  template:
    metadata:
      labels:
        name: ssd-monitor
    spec:
      containers:
      - name: main
        image: luksa/ssd-monitor
      terminationGracePeriodSeconds: 30